### ISSUE TITLE
Unable to run (paths issue?)

### ISSUE THREAD

**Issue by daurnimator** [PaulBernier/castl#14]
Trying to run without linking:

```
$ ./bin/castl.js 
lua5.2: cannot open ./.code.js.lua: No such file or directory
```

Trying to run after `npm link`:

```
$ castl 
lua5.2: ./.code.js.lua:1: module 'castl.runtime' not found:
	no field package.preload['castl.runtime']
	no file '/usr/share/lua/5.2/castl/runtime.lua'
	no file '/usr/share/lua/5.2/castl/runtime/init.lua'
	no file '/usr/lib/lua/5.2/castl/runtime.lua'
	no file '/usr/lib/lua/5.2/castl/runtime/init.lua'
	no file './castl/runtime.lua'
	no file '/home/daurnimator/.luarocks/share/lua/5.2/castl/runtime.lua'
	no file '/home/daurnimator/.luarocks/share/lua/5.2/castl/runtime/init.lua'
	no file '/usr/share/lua/5.2/castl/runtime.lua'
	no file '/usr/share/lua/5.2/castl/runtime/init.lua'
	no file '/usr/lib/lua/5.2/castl/runtime.so'
	no file '/usr/lib/lua/5.2/loadall.so'
	no file './castl/runtime.so'
	no file '/home/daurnimator/.luarocks/lib/lua/5.2/castl/runtime.so'
	no file '/usr/lib/lua/5.2/castl/runtime.so'
	no file '/usr/lib/lua/5.2/castl.so'
	no file '/usr/lib/lua/5.2/loadall.so'
	no file './castl.so'
	no file '/home/daurnimator/.luarocks/lib/lua/5.2/castl.so'
	no file '/usr/lib/lua/5.2/castl.so'
stack traceback:
	[C]: in function 'require'
	./.code.js.lua:1: in main chunk
	[C]: in ?
```

After `cd lua`:

```
 $ castl 
/home/daurnimator/src/castl/bin/castl.js:170
        throw new SyntaxError("Couldn't transpile JS code: " + e);
        ^

SyntaxError: Couldn't transpile JS code: Error: ENOENT: no such file or directory, open 'code.js'
    at /home/daurnimator/src/castl/bin/castl.js:170:15
    at Object.<anonymous> (/home/daurnimator/src/castl/bin/castl.js:292:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
```

**Comment by dcurgz** [comment]
See this: https://github.com/PaulBernier/castl/issues/11.
Also, use the option `--babel` to get rid of that transpile error.
